### ISSUE TITLE
Parse.User.current() doesn't update local storage.

### ISSUE THREAD

**Issue by martolini** [ParsePlatform/Parse-SDK-JS#65] opened 2015-10-24 21:12 UTC
`Parse.User.current()` updates on `save()` in the _current_ session - but if you do a browser refresh (F5/CMD+R) the content is lost. The only way to update it is to force a `logOut()` and then `logIn()` again. `Parse.user.current().fetch()` is supposed to bring the `localStorage` up to date - but that is not happening.

Let me know if you need any more to reproduce.

**Comment by Sikandarkhan** [comment] 2015-10-25 09:16
User is being logged out everytime he quits the app. Let me know, If I can get help from localStorage () function?

**Comment by andrewimm** [comment] 2015-10-26 04:07
Under the hood, we update an in-memory cache of the current user, but we don't save back to disk on each successive server save.

The solution is to special-case the save of a `ParseUser` object, checking to see if it is the current user; if it is, we can save back to `localStorage` before resolving the outermost Promise.

**Comment by GauravButola** [comment] 2015-11-07 19:29
Is this a regression in the latest version? Because; I have `1.5.0` in one of my projects where saving the current parse user saves the object to localStorage as well, but on the other project where I'm using `1.6.7` I'm having this issue; the object doesn't persist in localStorage.

Same for `fetch()` the latest version only saves the current user to memory not localStorage but the earlier version I'm using updates localStorage as well.

**Comment by andrewimm** [comment] 2015-11-10 22:11
Just pushed a fix. We will release 1.6.9 later today with these issues resolved.

**Comment by bradyhigginbotham** [comment] 2015-11-17 21:13
Is 1.6.9 still being released? I see the tag in this repo, but site and CDN only have 1.6.7. Really need this fix in. Thanks!

**Comment by vection** [comment] 2015-12-06 16:54
Hi, just checking in to ask if 1.6.9 will be available soon? The CDN is still at 1.6.7 and I am also eager to distribute the fixed version.

**Comment by passcod** [comment] 2016-01-25 00:06
The CDN is at 1.6.14 at time of writing, the (recommended way of getting this aka the) npm module is at 1.6.14, this is fixed and should be closed.

**Closed** 2016-01-25 01:41 UTC
