### ISSUE TITLE
matchesQuery API on a Relation gives error code 102

### ISSUE THREAD

**Issue by jclalala** [ParsePlatform/Parse-SDK-JS#10] opened 2015-09-23 01:58 UTC
We have added a "joinCommunity" relation to the User object and use the following query.

new Parse.Query("User").matchesQuery("joinCommunity", new Parse.Query("Community").equalTo("objectId", "acMv7RpF1l")).find()

The above gives the following error in SDK v1.6.2:
{code: 102, message: "bad type for $inQuery"}

The SAME query works in v1.5.0.

**Comment by oriSomething** [comment] 2015-09-23 19:49
might be a bug over there, but why not using a simpler query like this one?
```js
var Community = Parse.Object.extends('Community');
var joinCommunity = Community.createWithoutData('acMv7RpF1l');

new Parse.Query('_User')
  .equalTo('joinCommunity', joinCommunity)
  .find()
```

**Comment by jclalala** [comment] 2015-09-24 00:16
We've used Relations for many-to-many relationship between User and Community objects. The query you suggested assumes many-to-one?

**Comment by oriSomething** [comment] 2015-09-24 09:19
i don't get it, you've presented a query for one to one relation, did i miss something?
if you want one to many, you can replace `equalTo` with `containedIn`. If you're taking about `Parse.Relation` you gave a wrong query from the beginning.

**Comment by jclalala** [comment] 2015-09-24 09:40
The query is not just for one-to-one, it can also work when "joinCommunity" attribute is a Relation. When the query is used on relation it returns "all User objects where joinCommunity matches objects returned by the inner query".

The reason why this is a bug is because the same code works on v1.5.0 and not v1.6.2 without modifying a line of code.

**Comment by oriSomething** [comment] 2015-09-24 09:42
interesting and good to know. i didn't know you can make `matcherQuery` on `Parse.Relation` objects

**Comment by andrewimm** [comment] 2015-09-28 22:24
@jclalala can you provide a reproducible test case? I've created what I believe is an analogous setup, and running a query shaped like the one you linked to above succeeds for me with the latest version of the SDK.

**Comment by jclalala** [comment] 2015-09-29 02:36
hi @andrewimm , please see below fiddlejs for case that has succeeded on v1.5.0.

https://jsfiddle.net/jclalala/x0owjbbs/9/

The same code that fails on v16.2:

https://jsfiddle.net/jclalala/x0owjbbs/

**Comment by andrewimm** [comment] 2015-09-29 02:50
Thanks @jclalala, that helped me pinpoint the issue. 
You have found a bug, but it should not be a problem if you properly construct your query -- you should be calling `new Parse.Query(Parse.User)`, not `new Parse.Query('User')`. See the documentation: https://parse.com/docs/js/guide#users-querying

By default, the JS SDK should rewrite `'User'` to `'_User'`, unless this behavior is turned off by the developer. While we enabled this feature for subclassing Parse.User in the new SDK, we neglected to do it on query construction as well, since all of our tests use the recommended `new Parse.Query(Parse.User)` form. I'll make sure the rewrite flag is taken into account, and close this issue when it makes its way into master, but we probably won't release 1.6.5 for another week or so.

In the meantime, just avoid the issue by replacing `'User'` with either `Parse.User` or `'_User'`

**Closed** 2015-09-30 22:11 UTC
Labels: needs more info
