### ISSUE TITLE
Parse.User.logOut doesn't destroy current user

### ISSUE THREAD

**Issue by albertolive** [ParsePlatform/Parse-SDK-JS#208] opened 2016-02-17 18:02 UTC
Hi!

I'm having an issue with Parse.User.logOut(). When I call that function, it doesn't remove from localStorage, as it did before, the keys related to Parse. The only thing I can do now is do it myself.

This is my code:

```javascript
logOut:function() {
    var that = this;
    var currentUser = Parse.User.current();
    currentUser.save().then(
        function(success) {
            Parse.User.logOut().then(
                function(success) {
                    var currentUser = Parse.User.current();
                    if (currentUser) {
                        //I have current user always.
                    }
                    that.history.pushState(null, '/login');
                },
                function(error) {
                    console.log(error);
                    that.history.pushState(null, '/main/404');
                }
            );
        },
        function(error) {
            console.log(error);
            that.history.pushState(null, '/main/404');
        }
    );
```

In localStorage I have this two parse related keys:

| Key        | Value           |
| ------------- |:-------------:|
| Parse/bU9RT7hUMWEtPrh310AjXXXXXXXXXXXXXXXXX/currentUser      | {"username":"albert....". ".."} |
| Parse/bU9RT7hUMWEtPrh310AjXXXXXXXXXXXXXXXXX/currentUser      | 47dc451d-b66f-55e8-f405-xxxxxxxxxx |

The only thing changed in localStorage when I press logout is with `sessionToken`, that's missing.

I haven't changed anything in past month and I'm using React but not using Parse-React.

`
"parse": "^1.6.0",
"react": "^0.14.3",
`

**Comment by andrewimm** [comment] 2016-02-17 18:16
I see. So, two fields are placed in localstorage when you use the Parse SDK. The first in your example above is the cached version of the user, which is used to re-inflate the user on login. This should definitely be cleared when we log the user out. I'll put out a fix for this.
The second is the unique installation ID, which is used to track analytics for your app. This shouldn't get cleared.

**Comment by andrewimm** [comment] 2016-02-17 19:22
Looking at the code, I see no reason why the user would still be on disk, and I can't reproduce this on my own. I've added an extra test to the ParseUser test suite to verify that the SDK behaves as intended.

Unless you can provide a stand-alone, reproducible test case, I'm afraid I can't do much to help.

**Comment by albertolive** [comment] 2016-02-18 10:39
Hi @andrewimm,

Thank you for your responses. I have downloaded blank project from Parse website and It works. It uses Parse version 1.6.14. Then I have downgraded my project and now it works. So I suppose that it comes from higher versions.

Thanks!

**Closed** 2016-02-19 01:33 UTC
Labels: needs more info
