### ISSUE TITLE
Frequent timeouts, ECONNRESET, and ECONNREFUSED on Node 0.12.7

### ISSUE THREAD

**Issue by KevinNuut** [ParsePlatform/Parse-SDK-JS#64] opened 2015-10-22 19:34 UTC
We receive frequent timeouts, ECONNRESET, and ECONNREFUSED responses to Parse queries, saves, and updates. This is with Parse JS SDK 1.5.0 running on NodeJS 0.12.7, though we have experienced this issue for a while on our databases across various previous versions.

"Received an error with invalid JSON from Parse: Error: connect ETIMEDOUT\n at     exports._errnoException (util.js:746:11)\n at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)"

"Received an error with invalid JSON from Parse: Error: read ECONNRESET\n at exports._errnoException (util.js:746:11)\n at TCP.onread (net.js:559:26)"

"Received an error with invalid JSON from Parse: Error: connect ECONNREFUSED\n at exports._errnoException (util.js:746:11)\n at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)"

We have no timeout issues with any of our other third party API calls, including logging and various mongodb stores. We've reviewed our maxSockets and other request() calls inside our own Node.JS code. We are normally processing 156 requests per minute, with 450 Parse JS SDK queries and saves per minute. We receive roughly 1 timeout or ECONN* message every 2 minutes.

I'm worried this will just be marked as "not a bug" of the JS SDK specifically, but we are having difficulty getting any feedback or support on these frequent issues through any of the Parse channels.

**Comment by TylerBrock** [comment] 2015-10-22 19:40
I'm having the same issue. I filed a bug report here if you want to add additional input: https://developers.facebook.com/bugs/777781325661733/

**Comment by bblurock** [comment] 2015-10-23 08:03
We are also facing this ECONNRESET issue especially while performing saving , we use latest Parse JS SDK 1.6.7 with NodeJS 4.0.0 and we're hosting on Heroku as well.

We've test the saveAll API with a very simple script which generates 3000 records with timestamp and splice into 100 records per batch saving.

```javascript
_parse.Cloud.useMasterKey();

var i, pages, promise;
var testPrototype = _parse.Object.extend("test");
var perBatch = 100;
var data = [];

for (i = 0; i < 3000 ; i++ )
{
    var test = new testPrototype();
    test.set("ts", (new Date).getTime());
    data.push(test);
}

// Calculation of total pages
pages = Math.floor(data.length / perBatch);
pages = (data.length % perBatch) > 0 ? pages + 1 : pages;
promise = _parse.Promise.as(0);

for (i = 0; i < pages ; i++)
{
    promise = promise.then(function(k)
    {
        var spliceAmount = data.length > perBatch ? perBatch : data.length;
        var dataToSave = data.splice(0, spliceAmount);

        return _parse.Object.saveAll(dataToSave).then(
            function(objs)
            {
                console.log("Saved Page. " + k);

                return _parse.Promise.as(k+1);
            },
            function(e)
            {
                console.log(JSON.stringify(e));

                return promise.reject("Save error");
            }
        );
    });
}
```

On Heroku, <b>every time</b> when it saved around 17xx records, the script will be abruptly shut down without catching any error response in the error promise.

Here is the error message I got from node-inspector:

```
unhandled res:{"seq":1458,"type":"event","success":true,"running":true,"event":"Network._requestWillBeSent","body":{"requestId":"103"}}

unhandled res:{"seq":1459,"type":"event","success":true,"running":true,"event":"Network.loadingFailed","body":{"requestId":"103","timestamp":1445575.700141,"type":"XHR","errorText":"ECONNRESET","canceled":false}}

unhandled res:{"seq":1460,"type":"event","success":true,"running":true,"event":"Network._loadingFailed","body":{"requestId":"103"}} 
```

**Comment by TylerBrock** [comment] 2015-10-23 14:42
Thanks @bblurock I would encourage you to subscribe to the Facebook bug report so that this gets greater visibility. It doesn't look like we will get any response here.

**Comment by wangmengyan95** [comment] 2015-10-23 21:12
Hi @KevinNuut and @TylerBrock, our backend guys are investigating this issue. Since it is not a JS-client side issue, let's discuess it in the [bug tools](https://developers.facebook.com/bugs/777781325661733/).

**Comment by TylerBrock** [comment] 2015-10-24 21:07
@bblurock, please post your repro in the but report ticket so that they look at it.

**Comment by bblurock** [comment] 2015-10-25 13:27
@TylerBrock Sure. I'll post to the report ticket later.

--

As for my particular example script. I further dived in to its behaviour on parse.

I've found out every promise of saveAll resolved almost immediately(1~10 millisecond) causing my request rate limit exhausted in few seconds, which never happened in my local environment.

Hence, I made a workaround with setTimeout. If the saveAll promise resolved latency is smaller than 1 second(I'm using the Parse free plan, 30 requests/second), I let it sleep the remaining time until my script fire another saveAll request.

The saving can finish without any ECONNRESET for now.

```javascript
_parse.Cloud.useMasterKey();

    var i, pages, promise;
    var testPrototype = _parse.Object.extend("test");
    var perBatch = 20;
    var data = [];

    for (i = 0; i < 3000 ; i++ )
    {
        var test = new testPrototype();
        test.set("ts", (new Date).getTime());
        data.push(test);
    }

    // Calculation of total pages
    pages = Math.floor(data.length / perBatch);
    pages = (data.length % perBatch) > 0 ? pages + 1 : pages;
    promise = _parse.Promise.as({"index": 0, "ts": (new Date).getTime()});

    for (i = 0; i < pages ; i++)
    {
        promise = promise.then(function(k)
        {
            var spliceAmount = data.length > perBatch ? perBatch : data.length;
            var dataToSave = data.splice(0, spliceAmount);
            var pagePromise = new Parse.Promise();

            Parse.Object.saveAll(dataToSave).then(
                function(objs)
                {
                    var ts = (new Date).getTime();
                    var diff = ts - k.ts;
                    // I'm using the free plan of parse, 30 request/per second
                    var threshold = 1000;

                    if (diff < threshold)
                    {
                        var toSleep = threshold - diff;

                        try
                        {
                            setTimeout(function(){
                                pagePromise.resolve({"index": k.index+1, "ts": (new Date).getTime()});
                            }, toSleep);
                        }
                        catch (e) {
                            console.log(JSON.stringify(e));
                        }
                    }
                    else {
                        pagePromise.resolve({"index": k.index+1, "ts": (new Date).getTime()});
                    }
                },
                function(e)
                {
                    console.log(JSON.stringify(e));
                    return promise.reject("Save error");
                }
            );

            return pagePromise;
        });
    }
```

**Comment by TylerBrock** [comment] 2015-10-25 15:41
I did the same thing :-), however I don't think this is a symptom of rate
limiting as we get these errors on single requests with zero other load.

**Comment by KevinNuut** [comment] 2015-10-26 16:48
Also, while this may be a platform issue, I think there is a bug here in that Parse JSON cannot properly handle the ETIMEOUT, ECONNRESET, or ECONNREFUSED responses and instead reutnrs Parse error 107 of invalid JSON. Shouldn't it ideally return err code 100? Maybe this was already addressed in 1.6.7. 

http://parse.com/docs/dotnet/api/html/T_Parse_ParseException_ErrorCode.htm

**Comment by andrewimm** [comment] 2015-10-26 19:00
I'll look into this issue to see if there's a problem with the SDK or the `XMLHttpRequest` polyfill we use in Node.js. If we can't trace it to the SDK, though, you guys are correct that we will close this issue. We want to keep GitHub issues tied to the client SDKs. For backend / platform bugs, the Facebook Developers bug reporting flow is much better -- we have a dedicated team that helps reproduce and triage bugs, and we can collect information from individuals confidentially (for instance, we need real app ids to investigate this particular bug). Thanks for providing the information you already have there, we're actively investigating.

As far as I can tell right now, the only action that we can take on the SDK is to make sure errors from the `xmlhttprequest` third party module we use are translated to the appropriate client error codes, rather than getting grouped into "107: invalid JSON" errors. However, I think it's odd that this error only occurs on Node environments, so I'll do my best to dig into the code of `xmlhttprequest` and see if it might be doing some sort of inefficient socket handling that would affect a node client's ability to connect to Parse.

**Comment by KevinNuut** [comment] 2015-10-26 20:48
I think its just because these are Node System Errors occurring from http / net failures when the Parse server are rejecting or refusing the API calls. I've also noticed times when a call to the Parse API has return the Parse home page or an HTML error page, and in those instances as well, the xmlhttprequest does not know how to handle the HTML page returned.

https://nodejs.org/api/errors.html#errors_econnreset_connection_reset_by_peer

**Comment by TylerBrock** [comment] 2015-10-26 20:56
Thanks @andrewimm. It would be nice if the errors mapped correctly so that we can hypothetically handle them when they occur.

The underlying issue however, as you mention, is probably not SDK related and we have provided all related Application IDs to Facebook/Parse in the bug report ticket. I would be happy to help reproduce it with Parse/Facebook if you want. It is killing our reliability right now.

**Comment by andrewimm** [comment] 2015-10-26 21:14
Given the reproducible case above, I'm curious to see whether it's related to memory usage of `node-xmlhttprequest`. Did these issues start recently (without code changes), or are they tied to recent increases in outgoing requests?

If they started recently, I'd be looking at an Amazon-related explanation (Parse, Heroku, and Modulus are all AWS-hosted). Otherwise, my guess is that it's a memory issue in `node-xmlhttprequest`

**Comment by TylerBrock** [comment] 2015-10-26 21:32
Hi Andrew, from what I can tell our memory usage doesn't fluctuate at all. In our case it fails to connect, resets, and times out when it is the only **singlular** request going through our entire system.

We've had dozens of requests fail on our single dyno today and I've attached the memory usage graph for it (to summarize 76-78mb being used out of 1gb -- less than 1/13th the capacity of the dyno is being used.

![screenshot from 2015-10-26 14-29-53](https://cloud.githubusercontent.com/assets/280807/10743072/098aefda-7bee-11e5-897f-d92d64bfa701.png)

I'm not seeing this as a memory constraint issue at all.

**Comment by KevinNuut** [comment] 2015-10-26 21:32
It's difficult to say for my scenario. 

We upgraded a new release with Parse 1.6.7 the day Parse launched the Parse + Heroku announcement. We started getting memory alert issues, but that may have been related to how we were still working with currentUser() in 1.6.7 and Client.User.enableUnsafeCurrentUser();

After seeing memory issues, I rolled back to our stable build from 14 days prior (Parse 1.5.0 and without various currentUser() changes) and we started to notice the ECONNRESET and ECONNREFUSED. Unfortunately, our traffic had also increased by 50% from a marketing push on the same day so it became very difficult to isolate if the cause was our load or an issue in Parse.

I then noticed Tyler and others announcing the same issue that day. Our memory stays at max swap of 25MB and Max total of 500MB out of a 1GB limit. Our dyno load is > 1%.

**Comment by TylerBrock** [comment] 2015-10-26 21:34
We have a different scenario: Parse SDK 1.5, Node 4.3.1, and virtually zero load.

**Comment by TylerBrock** [comment] 2015-10-26 22:31
@andrewimm would you mind poking the other folks involved to see if they can look at the ticket again. We are dropping a large percentage of our requests in production here and our ticket isn't getting any attention. We'd appreciate any help you can provide. I will do whatever you all need in order to help and provide information.

**Comment by andrewimm** [comment] 2015-10-26 23:02
@TylerBrock I can assure you that we're actively investigating this issue, and that no poking is necessary.

**Comment by TylerBrock** [comment] 2015-10-26 23:09
ok thanks!

**Comment by KevinNuut** [comment] 2015-10-26 23:24
The following is an update from Heroku and their investigation from their platform team. Note that I am now seeing up to 15% to 25% of failures as of the last two hours.

"Hi there,

We took a look at the backend runtime server a dyno that experienced this was running on and the server seemed fine at the time. There weren't any performance issues (high CPU load average, swapping, network congestion, etc.) at the time and no other apps on that server were experiencing problems either. ECONNRESET and ECONNREFUSED errors are generated from the receiving end, so in this case those errors are basically the remote end hanging up on you. If Parse can get any more information on why that's happening on their end we might be able to look into this in more detail, but from what I can see in our metrics everything was working well.

I'm not sure exactly what Parse is using in their backend, but there's an interesting thread here about a situation where Unicorn behind a reverse proxy like Nginx can sometimes cause ECONNRESET errors if all the data in rack.input isn't being drained on every request. It sounds like that only happens on larger requests though. That may or may not have any bearing on the issue at hand (their architecture could completely rule that out as a possibility depending on what they're using), but that at least illustrates how something like this can happen on the remote side.

Thanks,
-Joel"

**Comment by andrewimm** [comment] 2015-10-26 23:48
Closing out as this has been resolved.

**Closed by andrewimm** 2015-10-26 23:48 UTC

**Comment by TylerBrock** [comment] 2015-10-27 18:34
@andrewimm do you want me to make a new ticket for properly handling the connection failures and translating them to a promise rejection rather than an exception?
