### ISSUE TITLE
Sometimes query.find never triggers a callback - NodeJS npm module

### ISSUE THREAD

**Issue by arethtapslots** [ParsePlatform/Parse-SDK-JS#70] opened 2015-10-27 22:43 UTC
I am seeing cases where I make a query.find call along with query.equalTo to the User table and a success or error callback never gets triggered.

To reproduce, get a list of User table object ids (about 4000), then do a query.find call where query.equalTo(objectId, objectIdValue). You will see that once in a while, it will never trigger error or success callbacks.

As far as I can tell from the docs, those are the only two callback options.

**Comment by TylerBrock** [comment] 2015-10-28 04:00
This happens to us as well. We have promises from `find()`, `saveAll()`, etc... that are neither resolved or rejected (never fulfilled).

I believe this happens when Parse's API times out, which seems to be often.

**Comment by arethtapslots** [comment] 2015-10-28 16:31
I kind of figured it was related to the timeout issue. Here is the bug report link: https://developers.facebook.com/bugs/777781325661733/

Although that bug is on the platform side, the docs for this npm module state that either an error callback will trigger or a success callback will trigger, on a timeout an error callback should trigger. You cant not callback on anything, thats terrible.

**Comment by TylerBrock** [comment] 2015-10-28 16:42
That is correct. The problem is that the failure to deserialize the returned response as JSON is getting thrown as an error by Node inside of the Parse JS SDK. Parse promises are not A+ compliant so those thrown errors do not get translated into rejected promises.

**Comment by andrewimm** [comment] 2015-10-28 19:20
Merging this into #71. As noted, this is because the polyfill we use on node was not behaving exactly as an XHR, but this should be fixed in 1.6.8 later today. The commit is already in the tree.

**Closed by andrewimm** 2015-10-28 19:20 UTC
