### ISSUE TITLE
Valid Parse.User.current() immediately after Parse.User.logOut()

### ISSUE THREAD

**Issue by andresgarza** [ParsePlatform/Parse-SDK-JS#219] opened 2016-03-07 07:06 UTC
Retrieving the current user immediately after logging out still returns a valid User:

```
Parse.User.logOut();
Parse.User.current(); // returns previous User
```

I'm not entirely sure whether this is intended or not, as the code for `logout` does use `currentUserAsync`, but the documentation in the Developers Guide does imply that the current user should be null immediately after calling `logOut`:

<img width="624" alt="screen shot 2016-03-07 at 12 27 19 am" src="https://cloud.githubusercontent.com/assets/154718/13562209/791009ec-e3fb-11e5-9106-28b08908e0c8.png">

**Comment by daleee** [comment] 2016-03-08 04:38
I've been having issues with `Parse.User.logOut()` as well. In fact, on v1.7.1 of the JS SDK, it seems that logOut() either doesn't work or logs you back in automatically (for me at least).

As of v1.6.14, it seems to work. As soon as you install v1.7.0, it seems to break again. So I've moved back to v1.6.14 for now.

**Comment by andrewimm** [comment] 2016-03-15 15:54
@andresgarza unless you can provide a small example that reproduces this, forgive me for being skeptical. I can point you to multiple tests in the codebase that check this exact behavior, as well as the piece of async. Every time someone raises this issue, it tends to be a mistake on their fronts.

@daleee do you mean you're having issues with `parse-react`? The issue with #200 was not an issue with this SDK, but a problem with the assumptions `parse-react` makes about legacy promises.

**Comment by andrewimm** [comment] 2016-03-15 15:57
Actually, I've taken another look, and the Promise behavior changes make this behavior explicitly asynchronous. We've been recommending that people should treat `logOut` as asynchronous since at least version 1.5, so this is mostly an issue with out-of-date docs. I'll publish an update to those, closing this as by-design.

**Closed by andrewimm** 2016-03-15 15:57 UTC

**Comment by yamill** [comment] 2016-03-15 20:18
@andrewimm so is this the solution?

```
Parse.User.logOut().then(function(){
          console.log(Parse.User.current());
        }, function(error){
          console.log(error);
        });
```

I am confused. Because, when i try this the User session does not return null - instead it's still returning the user object.

**Comment by yamill** [comment] 2016-03-15 20:33
I ended up install Parse 1.6.13 and was able to logout the user just fine. Not sure why it doesn't work with 1.7.0+. I look forward to hopefully seeing an update that fixes this issue.

**Comment by andrewimm** [comment] 2016-03-15 20:33
That should be the solution, yes. By the time logOut has finished executing, both the cache and the on-disk entry should be null. I'll look further into why you might be seeing what you're seeing.

**Comment by andrewimm** [comment] 2016-03-15 20:33
All I know is that all of my personal tests have worked fine. Until I can find a reliable repro, I can't do much to address this.

**Comment by yamill** [comment] 2016-03-15 20:34
If it helps I'm using React-Native. I am also including Parse this way:

```var ParseReact = require('parse-react/react-native');```

**Comment by andrewimm** [comment] 2016-03-15 20:35
That does help. On react native, the source of truth is `currentAsync()`, not `current()`, since the cache needs to be initially populated from the disk. Still, the cache _should_ be invalidated, so I'll look further into the async codepath.

**Comment by yamill** [comment] 2016-03-15 20:45
Thanks for looking into this. Yeah I tried ``currentAsync`` and it still no luck. That's what I was thinking, it should of still been invalidated.

This is my case scenario:

```

var Parse = require('parse/react-native');
var ParseReact = require('parse-react/react-native');
Parse.initialize(PARSE_APP_ID);
Parse.serverURL = PARSE_SERVER_URL;

var myapp = React.createClass({
  mixins: [ParseReact.Mixin],
  observe: function(){
    return {
      user: ParseReact.currentUser
    }
  },
  render() {

    if(!this.data.user){
      return <Authenticate />;
    }

    return <Main />
  }
});
```

Then inside my Main component I have a button that executes:

````
Parse.User.logOut();
```

This works fine with 1.6.13 - upon clicking logout it will switch from Main to Authenticate component.

In 1.7.0, I am able to keep the user logged in. Logout appears to execute if I run it with a Promise, but even on success it doesn't clear the session.

**Comment by andrewimm** [comment] 2016-03-15 20:59
Okay, you didn't mention you were using `parse-react`. As pointed out above, ParseReact only supports the JS SDK up to 1.6.*. This is due to the way it wraps the default logout behavior. I've been meaning to push out a patch. I just haven't had the time.
Again, the JS SDK is operating as intended. `parse-react` just needs an update to handle 1.7 and beyond.

**Comment by yamill** [comment] 2016-03-15 22:13
Ah gotcha. Well the weird thing is that I even tried the following:

```
var Parse = require('parse/react-native');
var ParseReact = require('parse-react/react-native');
Parse.initialize(PARSE_APP_ID);
Parse.serverURL = PARSE_SERVER_URL;

var myapp = React.createClass({
  render() {

    if(!Parse.User.currentAsync()){
      return <Authenticate />;
    }

    return <Main />
  }
});
```

And it still didn't work with 1.7.0. I had also removed parse react as well when I tried this.
Maybe it works on the browser (I'll try that - and let you know) but in RN it wasn't working for me.

**Comment by andrewimm** [comment] 2016-03-15 22:16
As I mentioned, Parse+React is not compatible with 1.7.*

**Comment by yamill** [comment] 2016-03-15 22:23
Oh ok. I understand now, sorry I thought you meant the ParseReact library.

**Comment by andrewimm** [comment] 2016-03-15 22:24
Ah, I do.  I was going by your original post before you edited it. Using the Parse SDK with React, _without the ParseReact library_ should still work fine.

**Comment by andrewimm** [comment] 2016-03-15 22:25
The reason your code doesn't work is because `currentAsync()` returns a Promise, which is always truthy :)
