### ISSUE TITLE
Returning a ParseObject that has been turned into JSON from Cloud Code reverts pointers back to ParseObjects when received on frontend

### ISSUE THREAD

**Issue by ibrennan** [ParsePlatform/Parse-SDK-JS#258] opened 2016-04-14 14:45 UTC
**Version affected: **1.8.2 (and previous)
**Enviroments:** Node.JS v4.4.3, OSX El Capitan Chrome 49.0.2623.110
**Steps to reproduce:**

1. Create some dummy data:
```javascript
var Post = Parse.Object.extend("Post");
var Comment = Parse.Object.extend("Comment");

var myPost = new Post();
myPost.set("title", "I'm Hungry");

var myOtherPost = new Post();
myOtherPost.set("title", "I'm not hungry now");

var myComment = new Comment();
myComment.set("content", "Let's do Sushirrito.");
myComment.set("parent", myPost);
myComment.save();

var myOtherComment = new Comment();
myOtherComment.set("content", "Glad you enjoyed your lunch");
myOtherComment.set("parent", myOtherPost);
myOtherComment.save();
```

2. Now let's write a simple cloud function to get the data, and turn it all into JSON and return to frontend. If you run the following you'll notice that the console logged comments variable is correctly represented as a nested Object...
```javascript
Parse.Cloud.define('getComments', function(request, response){
	var Comment = Parse.Object.extend("Comment");
	var query = new Parse.Query(Comment);
	query.include('parent');
	query.find({
		success: function(comments) {
			console.log('comments pre .toJSON()', comments);
			comments = comments.map(function(comment) {
				return comment.toJSON();
			});

			// At this point comments is correctly format JSON:
			console.log('comments post .toJSON()', comments);

			// Return the JSON to frontend:
			response.success(comments);
		},
		error: function(e) {
			console.error(e);
			response.error(e);
		}
	});
});
```

3. When calling the above code you'd expect it to return that same Object to the frontend, but instead what happens is this:
```javascript
Parse.Cloud.run('getComments', {}).then(function(comments) {
	console.log('getComments result:', comments);
}, function(error) {
	console.error(error);
});
```

**Summary**
Something appears to happen to the Object between the response.success() and the resolved data from Parse.Cloud.run()

**Server side console.log result:**
![screen shot 2016-04-14 at 15 40 12](https://cloud.githubusercontent.com/assets/1170905/14531984/4222997a-0257-11e6-88da-63c337b04ebe.png)

**Frontend result:**
![screen shot 2016-04-14 at 15 40 25](https://cloud.githubusercontent.com/assets/1170905/14531990/48b08630-0257-11e6-8fa7-e6d244d68bb7.png)

**Comment by ibrennan** [comment] 2016-04-14 14:58
Just to further compound the potential bug, on the Cloud Code if we do:

```javascript
response.success(JSON.stringify(comments));
```
This will mean the response is sent as a String representation of the JSON. On the frontend we then parse the String and turn it back into JSON:
```javascript
comments = JSON.parse(comments);
```
This results in the correctly formatted JSON representation of the data

**Comment by andrewimm** [comment] 2016-04-14 15:04
Every response coming from the server is decoded to re-inflate special types that don't have a native JSON representation: `Date`, `Parse.File`, `Parse.GeoPoint`, etc. This also happens for `Parse.Object`. Any time an object comes back with a `__type` field, the SDK interprets it as an object that needs to be inflated. This is exactly the intended behavior, and the only way the SDK can work in the first place.

To pass back objects that you don't want to be inflated, you'd want to avoid passing the `__type` field back. Here's the confusing part... the brief view of output you include above shows the `__type` fields, but calling `toJSON()` in your code as described would not include that field, nor the `className` field. Here's the relevant code: 
https://github.com/ParsePlatform/Parse-SDK-JS/blob/master/src/ParseObject.js#L410

I'm going to need some more information, because the code you wrote shouldn't be outputting the output you provided, and the output you provided would be expected by design to produce the client counterparts you're seeing.

**Comment by ibrennan** [comment] 2016-04-14 15:27
Thanks for the speedy reply @andrewimm, makes sense about what you're saying regarding the re-inflating of types.

I can't see the in the code you linked to where __type and className get stripped out though? I followed it back to the encode.js and couldn't see reference to it there.

Would you like anything more from me, it seems like we should be able to reproduce the __type and className field removal issue in a simple script

**Comment by andrewimm** [comment] 2016-04-14 15:38
Sorry, I was trying to point out that the two fields aren't added in the first place, not that they're stripped out. When actual Parse Objects are passed back to the client from cloud code, the middleware calls a private method called `_toFullJSON()` to add those missing fields.

For now, could I just get the full console output of the cloud code you've included above? If necessary, I'll ask you for a repro case later.

**Comment by ibrennan** [comment] 2016-04-14 15:46
Here's the output of ``comments``, which is the array result of the .find():

```
[ ParseObjectSubclass { className: 'Comment', _objCount: 0, id: 'Ems4SSqa6w' },
  ParseObjectSubclass { className: 'Comment', _objCount: 2, id: 'glwheqifgI' },
  ParseObjectSubclass { className: 'Comment', _objCount: 4, id: 'xv3pofphRb' },
  ParseObjectSubclass { className: 'Comment', _objCount: 6, id: 'BViHmBCEhX' },
  ParseObjectSubclass { className: 'Comment', _objCount: 8, id: '6mOLGIC7OY' },
  ParseObjectSubclass { className: 'Comment', _objCount: 10, id: 'bONunA0osL' },
  ParseObjectSubclass { className: 'Comment', _objCount: 12, id: 'w7smqUS8T5' },
  ParseObjectSubclass { className: 'Comment', _objCount: 14, id: 'ZRrz4KRW8M' },
  ParseObjectSubclass { className: 'Comment', _objCount: 16, id: 'CZYFaopk3F' },
  ParseObjectSubclass { className: 'Comment', _objCount: 18, id: 'KAFQODiZ6H' } ]
```

Here's the output from the Object at index 0 in that array after calling .toJSON() on it:
```
{ content: 'Let\'s do Sushirrito.',
  parent:
   { title: 'I\'m Hungry',
     updatedAt: '2016-04-14T14:25:20.847Z',
     createdAt: '2016-04-14T14:25:20.847Z',
     objectId: 'te85roF7fv',
     __type: 'Object',
     className: 'Post' },
  updatedAt: '2016-04-14T14:25:20.919Z',
  createdAt: '2016-04-14T14:25:20.919Z',
  objectId: 'Ems4SSqa6w' }
```

The __type and className are only being exposed on the 'parent' key, which is a Pointer to another Class object.

**Comment by andrewimm** [comment] 2016-04-14 19:41
Okay. I'd actually classify all of this to be expected behavior. When encoding an object to JSON, we still expect that nested fields will contain the appropriate `__type` fields, since it's impossible to add these after the fact if they're desired. And since the `__type` fields are being passed, I'd expect the client the inflate these into Parse.Objects.

I'd recommend that you simply rewrite your delivery code to ensure the nested fields are also coming back in your expected format. Either something like:
```js
comments.map(function(comment) {
  var json = comment.toJSON();
  if (json.parent) {
    delete json.parent.__type;
  }
});
```

or write your own encoding function that only passes back the fields you need on the client, whitelist style.

Closing this as behaving as intended.

**Closed by andrewimm** 2016-04-14 19:41 UTC

**Comment by parkej60** [comment] 2016-08-25 02:24
How am I supposed to call .toJSON on the root level object and the loop through it and call .toJSON on all of it's properties as well? For instance what if I have a Date, Parse.File and Parse.GeoPoint all associated to this one object? Maybe I'm missing something, but this seems really awkward to me.

**Comment by andrewimm** [comment] 2016-08-25 19:44
@parkej60 `toJSON` recursively calls `toJSON` on all its nested children as well. The reason this whole thing seems awkward is because it is not the way you are supposed to return a Parse Object from Cloud Code. If you call `response.success()` with your result, the encoding is properly done for you.

**Comment by parkej60** [comment] 2016-08-29 23:09
@andrewimm I am using response.success, but not directly return parse objects from Cloud Code. I'm sending something like this response.success({"queryIdentifier":0,"results":restaurantArray});

**Comment by andrewimm** [comment] 2016-08-29 23:15
@parkej60 you should be able to call exactly that, and it should work. If `restaurantArray` is an array of viable Parse Objects, it should encode properly.

**Comment by parkej60** [comment] 2016-08-29 23:21
Well, I'll keep digging into it then I guess.

**Comment by parkej60** [comment] 2016-08-29 23:25
@andrewimm Ok So here's an interesting example.

`          var Restaurant = Parse.Object.extend("Restaurant");
            var query = new Parse.Query(Restaurant);
            query.limit(20);
            query.descending('rating');
            query.find().then(function(restaurants){
                view.$el.html(view.template({restaurants:restaurants}));
            },function(error){
                console.error("Error: " + error.code + " " + error.message);
            });`

This also returns the objects in the format and it's a direct server query. 
```
{
_objCount: 0
className: "Restaurant"
id: "NtfeOn3dFH"
}
```

**Comment by arladmin** [comment] 2020-08-24 11:39
Hi @parkej60 , were you able to work out a solution for this?
As this still seems to be an issue, at least in my case.

**Comment by tiavina-mika** [comment] 2020-11-30 14:22
Hi! so finally is there any solutions for this issue?
