### ISSUE TITLE
Parse cloud code date and time conversion to GMT

### ISSUE THREAD

**Issue by srameshr** [ParsePlatform/Parse-SDK-JS#130] opened 2015-12-20 10:58 UTC
From client code:
```Date```: ``` Sun Dec 20 2015 00:00:00 GMT+0530 (IST)```
```Time```:```Sun Dec 20 2015 16:24:00 GMT+0530 (IST)```

This is getting converted into GMT format on Parse Cloud like this:

// Logging the same object that I sent, via ```request.params```
```Date```: ```2015-12-19T18:30:00.000Z``` ```//Surprisingly it is one day behind now ? ```
```Time```:```2015-12-20T10:54:00.000Z``` ```// Time is -5:30 hours but surprisingly it has not changed date to a day behind```

How do I prevent it?

**Comment by jeveloper** [comment] 2015-12-20 18:47
This is designed in such a way so that its universal.
I suggest using momentjs library and moment-tz  so you can work with any timezone.

This is NOT a bug.

**Comment by srameshr** [comment] 2015-12-21 01:27
I will try it out

**Comment by andrewimm** [comment] 2015-12-21 08:38
Closing this as by design. As @jeveloper notes, dates in GMT are considered universal. In JavaScript, dates have no inherent time zone. They are simply represented internally as a number of milliseconds from the Unix Epoch. Browsers and JS server environments print dates in the local timezone, and methods such as `getMonth()`, `getDate()`, and `getFullYear()` are relative to the timezone of the execution environment. [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) has a great reference for all of the functionality / methods of Date objects, and I definitely recommend using a library like `moment.js` for managing dates.

**Closed by andrewimm** 2015-12-21 08:38 UTC

**Comment by srameshr** [comment] 2015-12-21 12:13
I am not getting it. Is there any rules / guidelines that I have to follow while using dates on Parse?
Right now I am just passing a date object to the cloud. It is getting converted there. So, what format should I pass / convert before performing save operation?

In my case, I will be retrieving rows based on date value.

**Comment by jeveloper** [comment] 2015-12-21 15:28
@srameshr You should really read the guide for parse documentation, it does describe that dates are stored in GMT.
As mentioned there are many ways of adjusting them to any timezone.
In javascript i use moment + moment.tz which is super easy.

Also querying dates is pretty simple, just assume that you need to convert a passed date in GMT timezone , so if you're in India , just convert date to (-5 hours).

**Comment by srameshr** [comment] 2015-12-21 16:36
I think I did that already. I am facing some weird issue in conversion. If I just add moment.tz(date).format() I get 400 Bad request. If I do the same on my browser it just works fine. 

I cant figure out where am I going wrong

**Comment by andrewimm** [comment] 2015-12-21 17:28
@srameshr you need to include the moment.js library in your `/cloud` directory, so that you can require it. You'll either need to fetch it from their web site, or from npm.

**Comment by srameshr** [comment] 2015-12-22 07:01
@andrewimm I have included it. The moment version was 1.7.2 so I have included the latest version and did ```require('moment-2.8')``` and ```require('moment-tz-master')```

**Comment by srameshr** [comment] 2015-12-23 02:31
Finally! This answer helped me in understanding: http://stackoverflow.com/questions/18014341/how-to-convert-time-correctly-across-timezones
