### ISSUE TITLE
Bug on Parse.Query, trying to include keys but the server doesn't fetch the information

### ISSUE THREAD

**Issue by RafaRuiz** [ParsePlatform/Parse-SDK-JS#50] opened 2015-10-13 17:56 UTC
Hello. I'm mostly Android and iOS developer. I've always created my own backend for Android or iOS, so when I had some tables with pointers and I needed the information, I used to do my `query` including keys by `include(String string)` or the iOS version: `[PFObject includeKey:NSString* key]` and I get my pointers fetched.

Now I'm trying to do another project, which envolves the Javascript SDK on CloudCode and the pointers were not being fetched at the end... for more details, please see my question on StackOverflow: http://stackoverflow.com/questions/33059768/parse-com-javascript-sdk-using-include-but-not-working?noredirect=1#comment54030428_33059768

Changing the file `/path/to/parse_project/.parse.project` (hidden), I changed the `"jssdk" : "latest"` for `"jssdk" : "1.4.2"` so basically I downgraded my version, and it works perfectly now.

So I think it's a bug in the Javascript SDK.

**Comment by andrewimm** [comment] 2015-10-13 18:57
Duplicate of #32

**Closed by andrewimm** 2015-10-13 18:57 UTC
Labels: duplicate

**Comment by RafaRuiz** [comment] 2015-10-14 18:00
Sorry about that, thank you for closing it.
