### ISSUE TITLE
Parse catches exceptions in callbacks and does not rethrow them

### ISSUE THREAD

**Issue by GoingUpInSmoke** [ParsePlatform/Parse-SDK-JS#228] opened 2016-03-18 11:45 UTC
Hi,

I have a problem using Parse SDK 1.7.1 

The code below just exists silently, although it should crash at line obj.field = 0;.

Seems like Parse catches this exception and does nothing.

I checked Parse SDK version 1.5.0 and the same code crashes with "TypeError: Cannot set property 'field' of undefined" as expected.

``` javascript
var MyObject = Parse.Object.extend('MyObject');
var query = new Parse.Query(MyObject);

var obj = undefined;

query.find({
  success: function(results) {
    obj.field = 0;
    console.log('done');
  },
  error: function(error) {
    console.error('error: ' + error.message);
  }
});
```

**Comment by andrewimm** [comment] 2016-03-18 16:28
This is actually somewhat by-design. In 1.7, the internal code managing promises was modified to more closely match the Promises/A+ spec. All internal code uses promises, and these Backbone-style callbacks are only tacked on at the end as part of that propagation. If an error occurs, it will be caught by the internal Promise handling logic, and will be propagated down the chain.
You can disable this behavior by calling `Parse.Promise.disableAPlusCompliant()` when your app initializes. That said, I highly recommend moving to the promises API. It's been the recommended method for years, and we are considering deprecating the callbacks interface to simplify the codebase.

**Comment by andrewimm** [comment] 2016-03-18 16:31
As an example, the following works as intended:
```js
query.find().then((results) => {
  obj.field = 0; // throws
  console.log('done'); // not called
}).fail((error) => {
  console.error('error: ' + error.message); // This runs
});
```

**Comment by GoingUpInSmoke** [comment] 2016-03-18 16:42
Thank you for the explanation.

**Closed** 2016-03-18 16:42 UTC
