### ISSUE TITLE
Parse cloud nuisance

### ISSUE THREAD

**Issue by srameshr** [ParsePlatform/Parse-SDK-JS#126] opened 2015-12-18 12:00 UTC
My afterSave trigger, has a line of code like this
 ```console.log(request.object.get("createdBy")) // {objectd: s83kdfds}```
And in the next line, if I do this:
``` var x = request.object.get("createdBy");
  console.log(x) // No message provided```

What is this?

And if i try to ```fetch``` or ```query``` a ```User``` inside my ```afterSave``` trigger, it returns ```'Message Not Provided'```


And, if I try to fetch a user in afterSave
```
var User = Parse.Object.extend('User');
      var query = new Parse.Query(User);
      query.equalTo("objectId", request.object.get("createdBy"));
      query.first({
        success: function(obj) {
          console.log("success man");
          console.log(obj)
        },
        error: function(err) {
          console.log("Error")

        }
      })
```

The output is:
``` 
success man
No message provided
```

What is this?

**Comment by wangmengyan95** [comment] 2015-12-18 19:18
Hi @srameshr, the User you want to query is your custom User object or a standard `Parse.User`?

**Comment by srameshr** [comment] 2015-12-18 19:36
It is a standard ```Parse.User```. I can get objects inside ```afterSave```. 
But what is with the logs saying ```Message Not Provided```.  A line above it  logs the object bot not on the next line. Object.keys() returns only few (className, id) props

**Comment by andrewimm** [comment] 2015-12-19 21:46
The issue is likely in the code you've provided above. `ParseQuery.first()` will call the success callback if the query was successful, which happens even if the object was not found (`first() is simply shorthand for getting the first element out of `find()`, which can return an empty array). In your case, you are searching where `'objectId' === { objectId: '...' }`, which will never happen, so we can expect `obj` to be undefined.

Also, the keys of an object are not [enumerable](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Enumerability_and_ownership_of_properties), so `Object.keys()` would not be expected to return them.

**Comment by srameshr** [comment] 2015-12-20 06:21
Yeah, that is what I am trying to say. If I try to save the key of ```{objectId: '...'}``` it just says ```Message not provided```

**Comment by andrewimm** [comment] 2015-12-21 08:40
I'm afraid I still don't understand the exact issue. Can you please provide a sample of code that reliably reproduces the error you mention?

**Comment by srameshr** [comment] 2015-12-21 18:50
Ok here is one problem I am facing: 
```
console.log(request.object);
/* Output */
 after_save triggered for SomeClass for user IyF1bfCJat:
  Input: {"object":{"ACL":{"*":{"read":true},"IyF1bfCJat":{"write":true}},"chatId":"-K5yzSvT6tSOAOXLTaUi","createdAt":"2015-12-20T10:44:48.462Z","createdBy":{"__type":"Pointer","className":"_User","objectId":"IyF1bfCJat"},"cuId":1,"opaque":"some of it","objectId":"Eq1TGseZdf","rRatingColor":"305D02","rThumb":"https://thecdn/1.jpg","req":[],"tags"... (truncated)
```

The data, is exactly like this.

Now here are some log values on this object:
```
  console.log("cuId"); // 1
  console.log("opaque"); // some of it
  console.log("objectId"); // No message provided 

```

What is with the last log? This is extremely frustrating.

**Comment by andrewimm** [comment] 2015-12-21 18:55
An object's id is available at `request.object.id`, not at  `request.object.get('objectId')`.

Closing as a use issue, not a bug.

**Closed by andrewimm** 2015-12-21 18:55 UTC
Labels: needs more info

**Comment by srameshr** [comment] 2015-12-21 19:01
Oh ok! I thought this applies only for the javascript SDK where you access id of the response object without using the ```get``` syntax. Thanks for this.

**Comment by srameshr** [comment] 2015-12-23 19:11
And it is back again! request.object.id is ```undefined``` AGAIN! This behaviour occurs randomly. I am running the same afterSave query, for a particular object. It returns ```undefined``` frequently.
